### ISSUE TITLE
Audit Logs pagination

### ISSUE THREAD

**Issue by szepeviktor** [Sucuri/sucuri-wordpress-plugin#22]
Was Audit Logs pagination disabled at some point?

Thanks.

**Comment by szepeviktor** [comment]
@cixtor Only "Audit Logs (50 latest logs)" is displayed.

**Comment by cixtor** [comment]
There was a bug in the code used to generate the links for the pagination, it was fixed with [commit 6794849](https://github.com/Sucuri/sucuri-wordpress-plugin/commit/6794849) and will be released with the rest of the changes for the next version of the plugin. Thanks for the report.

**Comment by szepeviktor** [comment]
Very nice.
