### ISSUE TITLE
PHP 5.5 reached end of life

### ISSUE THREAD

**Issue by szepeviktor** [Sucuri/sucuri-wordpress-plugin#26]
> Using an updated version of PHP (5.5.32)

(in green)

Please consider alerting users of 5.5
http://php.net/supported-versions.php

**Comment by ntorga** [comment]
Hi there,

Thanks for your suggestion. I'm aware this is quite late, but just to let you know, currently we're advising the use of at least 7.2 as it's the oldest PHP version with active and security support:
https://www.php.net/supported-versions.php

Regards,
Northon
