### ISSUE TITLE
Future commits

### ISSUE THREAD

**Issue by szepeviktor** [Sucuri/sucuri-wordpress-plugin#3]
Could you please overwrite all commits with a real date?

> Commits on Apr 8, 2016

**Comment by szepeviktor** [comment]
@cixtor Even GitHub is crunching it forever: https://github.com/Sucuri/sucuri-wordpress-plugin/graphs/contributors

**Comment by dcid** [comment]
@cixtor is way ahead of us all. Even in time.

**Comment by szepeviktor** [comment]
It is OK.
