### ISSUE TITLE
WAF cache not cleared on post update

### ISSUE THREAD

**Issue by hulet** [Sucuri/sucuri-wordpress-plugin#30]
When I update a Post on a site with the Sucuri WAF with Caching Enabled I expect this plugin to initiate request to clear the cache for the updated post but I don't see that happening.

Is that something we could add?

This can be done by hooking in to the `save_post` action.

**Comment by cixtor** [comment]
Feature request implemented with [commit #0525174](https://github.com/Sucuri/sucuri-wordpress-plugin/commit/0525174)
