### ISSUE TITLE
Speed-up release cycle

### ISSUE THREAD

**Issue by ale5000-git** [Sucuri/sucuri-wordpress-plugin#50]
Hi,
is it possible to speed-up the release cycle?

Best regards,
ale5000

**Comment by febane** [comment]
Hi,

Thanks for getting in touch. We are working on a plan to speed-up the release cycle to release new versions of the plugin on a monthly basis.

Do not hesitate to contact us if you have further questions.

Thanks!

**Comment by ale5000-git** [comment]
Thanks to you :)
