### ISSUE TITLE
Post-Type Alerts cannot dismiss post_type values containing numerical characters

### ISSUE THREAD

**Issue by luke-au** [Sucuri/sucuri-wordpress-plugin#70]
Hello,
I use the SEOPress/PRO plugin which creates a custom post type `seopress_404` and I receive Event: Post Update alerts with every new redirection created or edited as the Sucuri WordPress plugin doesn't allow me to add that post_type to the 'stop alerts from this post-type' list, returning an error message as the Sucuri plugin does not allow post types to be excluded when they contain numbers.

> `/wp-admin/admin.php?page=sucuriscan_settings#alerts`
> **SUCURI:** Only lowercase letters, underscores and hyphens are allowed.

The old WordPress Codex appears to be ignored by most developers as the `register_post_type` arguments for post_type are supposed to be **max. 20 characters, cannot contain capital letters, underscores or spaces**.
> [WordPress Codex - Function Reference/register post type](https://codex.wordpress.org/Function_Reference/register_post_type#post_type)

The newer WordPress Developer Code Reference parameters for post_type differs slightly saying **_Must not exceed 20 characters and may only contain lowercase alphanumeric characters, dashes, and underscores_** 
> [WordPress Developer Code Reference /functions/register_post_type](https://developer.wordpress.org/reference/functions/register_post_type/#parameters)

----
@wp-seopress
[SEOPress - Free - GitHub Repo](https://github.com/wp-seopress/wp-seopress)
[SEPPress - PRO](https://www.seopress.org/)

FYI: I also found another popular plugin using a number `vc4_templates` is created by "WPBakery Page Builder" formerly called “Visual Composer Page Builder”.
[WPBakery Page Builder](https://wpbakery.com/)

**Comment by ntorgagd** [comment]
Hello there,

This has been addressed by PR #79 which is waiting to be merged:
https://github.com/Sucuri/sucuri-wordpress-plugin/pull/79

Regards,
Northon

**Comment by ntorgagd** [comment]
@luke-au Could you please confirm this is no longer an issue on the last version of the plugin so we may close this topic?

**Comment by luke-au** [comment]
Yes, this no longer appears to be an issue. Thanks.
